const nouns = ['factory reset button',
'idiot',
'toaster',
'legend',
'psychic',
'sandwich',
'lettuce',
'kitty',
'friendly grandma',
'french chef',
'corn cake',
'candlestick maker',
'coffee pot',
'skinny woman',
'private investor',
'scourge upon the earth',
'rough-skinned newt',
'idea he suggested',
'hairy legs',
'mad-dog skullcap',
'sneaky criminal',
'dog poop',
'dragon',
'patrolman',
'pervert',
'toilet seat',
'really tough guy',
'multi-billionaire',
'mental disorder',
'chauvinistic pup',
'cheerful toilet seat',
'chilled good-for-nothing',
'chunky drug addict',
'cold-hearted Eskimo',
'contemporary queen',
'crazed master'];

module.exports = {
    nouns,
}
 