const verbs = ['surround',
    'stab',
    'medicate',
    'blindside',
    'trip',
    'swat',
    'harass',
    'trap',
    'sketch',
    'scatter',
    'challenge',
    'fight',
    'bury',
    'splatter',
    'smack',
    'trip up',
    'poke',
    'critique',
    'fear',
    'initiate',
    'run over',
    'schedule',
    'imprison',
    "don't underestimate",
    'cajole',
    'butter up',
    'sweet-talk',
    'shred',
    'dispute',
    'echo',
    'mimic',
    'berate',
    'castigate',
    'underrate',
    'taunt'];

    module.exports = {
        verbs,
    }